# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_janela(object):
    def setupUi(self, janela):
        janela.setObjectName("janela")
        janela.setWindowModality(QtCore.Qt.NonModal)
        janela.setEnabled(True)
        janela.resize(521, 452)
        janela.setMinimumSize(QtCore.QSize(521, 452))
        janela.setMaximumSize(QtCore.QSize(521, 452))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icones/Winrar/Winrar-com-chave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        janela.setWindowIcon(icon)
        janela.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(janela)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonIniciar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonIniciar.setGeometry(QtCore.QRect(10, 10, 61, 61))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonIniciar.setFont(font)
        self.pushButtonIniciar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icones/Controles de midias/play-dentro-de-um-círculo-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonIniciar.setIcon(icon1)
        self.pushButtonIniciar.setIconSize(QtCore.QSize(50, 50))
        self.pushButtonIniciar.setFlat(True)
        self.pushButtonIniciar.setObjectName("pushButtonIniciar")
        self.pushButtonParar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonParar.setEnabled(True)
        self.pushButtonParar.setGeometry(QtCore.QRect(150, 10, 61, 61))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonParar.setFont(font)
        self.pushButtonParar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icones/Controles de midias/pare-quadrado-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonParar.setIcon(icon2)
        self.pushButtonParar.setIconSize(QtCore.QSize(50, 50))
        self.pushButtonParar.setFlat(True)
        self.pushButtonParar.setObjectName("pushButtonParar")
        self.pushButtonPausar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPausar.setEnabled(False)
        self.pushButtonPausar.setGeometry(QtCore.QRect(80, 10, 61, 61))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonPausar.setFont(font)
        self.pushButtonPausar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icones/Controles de midias/pausa-circular-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonPausar.setIcon(icon3)
        self.pushButtonPausar.setIconSize(QtCore.QSize(50, 50))
        self.pushButtonPausar.setFlat(True)
        self.pushButtonPausar.setObjectName("pushButtonPausar")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 501, 211))
        self.tabWidget.setIconSize(QtCore.QSize(27, 27))
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setGeometry(QtCore.QRect(200, 0, 289, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(80, 20, 91, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 50, 91, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(180, 20, 21, 21))
        self.pushButton_6.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icones/Apagar/apagar-480.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon4)
        self.pushButton_6.setIconSize(QtCore.QSize(17, 17))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_7.setGeometry(QtCore.QRect(180, 50, 21, 21))
        self.pushButton_7.setText("")
        self.pushButton_7.setIcon(icon4)
        self.pushButton_7.setIconSize(QtCore.QSize(17, 17))
        self.pushButton_7.setObjectName("pushButton_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(200, 80, 289, 89))
        self.groupBox_3.setObjectName("groupBox_3")
        self.spinBoxLimiteMinimo = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBoxLimiteMinimo.setGeometry(QtCore.QRect(140, 20, 42, 21))
        self.spinBoxLimiteMinimo.setMinimum(1)
        self.spinBoxLimiteMinimo.setMaximum(9)
        self.spinBoxLimiteMinimo.setObjectName("spinBoxLimiteMinimo")
        self.spinBoxLimiteMaximo = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBoxLimiteMaximo.setGeometry(QtCore.QRect(140, 60, 42, 20))
        self.spinBoxLimiteMaximo.setMinimum(1)
        self.spinBoxLimiteMaximo.setMaximum(9)
        self.spinBoxLimiteMaximo.setObjectName("spinBoxLimiteMaximo")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 141, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(190, 20, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(190, 60, 61, 16))
        self.label_6.setObjectName("label_6")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(5, 0, 191, 169))
        self.groupBox.setObjectName("groupBox")
        self.checkBoxLetrasMaiusculas = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxLetrasMaiusculas.setGeometry(QtCore.QRect(10, 20, 171, 17))
        self.checkBoxLetrasMaiusculas.setObjectName("checkBoxLetrasMaiusculas")
        self.checkBoxLetrasMinusculas = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxLetrasMinusculas.setGeometry(QtCore.QRect(10, 40, 171, 17))
        self.checkBoxLetrasMinusculas.setObjectName("checkBoxLetrasMinusculas")
        self.checkBoxNumeros = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxNumeros.setGeometry(QtCore.QRect(10, 80, 171, 17))
        self.checkBoxNumeros.setObjectName("checkBoxNumeros")
        self.checkBoxSimbolos = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxSimbolos.setEnabled(True)
        self.checkBoxSimbolos.setGeometry(QtCore.QRect(10, 100, 171, 17))
        self.checkBoxSimbolos.setObjectName("checkBoxSimbolos")
        self.checkBoxLetrasAcentuadas = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxLetrasAcentuadas.setGeometry(QtCore.QRect(10, 60, 171, 17))
        self.checkBoxLetrasAcentuadas.setObjectName("checkBoxLetrasAcentuadas")
        self.checkBoxEspaco = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxEspaco.setGeometry(QtCore.QRect(10, 120, 171, 17))
        self.checkBoxEspaco.setObjectName("checkBoxEspaco")
        self.checkBoxTodos = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxTodos.setGeometry(QtCore.QRect(10, 140, 171, 17))
        self.checkBoxTodos.setObjectName("checkBoxTodos")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icones/Força bruta/winrarcommartelo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(7, 7, 91, 41))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icones/Pastas/abrir-pasta-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon6)
        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(7, 55, 91, 41))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icones/Sistema operacional/excluir-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon7)
        self.pushButton_5.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(105, 0, 384, 81))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_13 = QtWidgets.QLabel(self.groupBox_6)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        self.label_14.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_5.setGeometry(QtCore.QRect(120, 20, 91, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_6.setGeometry(QtCore.QRect(120, 50, 91, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_8.setGeometry(QtCore.QRect(220, 20, 21, 21))
        self.pushButton_8.setText("")
        self.pushButton_8.setIcon(icon4)
        self.pushButton_8.setIconSize(QtCore.QSize(17, 17))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_9.setGeometry(QtCore.QRect(220, 50, 21, 21))
        self.pushButton_9.setText("")
        self.pushButton_9.setIcon(icon4)
        self.pushButton_9.setIconSize(QtCore.QSize(17, 17))
        self.pushButton_9.setObjectName("pushButton_9")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(105, 80, 384, 89))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_15 = QtWidgets.QLabel(self.groupBox_7)
        self.label_15.setGeometry(QtCore.QRect(190, 20, 51, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        self.label_16.setGeometry(QtCore.QRect(290, 20, 51, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_7)
        self.label_17.setGeometry(QtCore.QRect(240, 20, 21, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_7)
        self.label_18.setGeometry(QtCore.QRect(340, 20, 31, 16))
        self.label_18.setObjectName("label_18")
        self.label_21 = QtWidgets.QLabel(self.groupBox_7)
        self.label_21.setGeometry(QtCore.QRect(10, 20, 31, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_7)
        self.label_22.setGeometry(QtCore.QRect(110, 20, 61, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_7)
        self.label_23.setGeometry(QtCore.QRect(110, 50, 71, 16))
        self.label_23.setObjectName("label_23")
        self.label_26 = QtWidgets.QLabel(self.groupBox_7)
        self.label_26.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_26.setObjectName("label_26")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icones/Dicionário/dicionário-480.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon8, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 0, 481, 171))
        self.groupBox_9.setObjectName("groupBox_9")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 20, 82, 21))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 50, 82, 21))
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_9)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 80, 421, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icones/Sistema operacional/processador-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon9, "")
        self.progressBarProgressoGeral = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBarProgressoGeral.setEnabled(True)
        self.progressBarProgressoGeral.setGeometry(QtCore.QRect(10, 390, 501, 31))
        self.progressBarProgressoGeral.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBarProgressoGeral.setProperty("value", 0)
        self.progressBarProgressoGeral.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBarProgressoGeral.setTextVisible(True)
        self.progressBarProgressoGeral.setOrientation(QtCore.Qt.Horizontal)
        self.progressBarProgressoGeral.setInvertedAppearance(False)
        self.progressBarProgressoGeral.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBarProgressoGeral.setObjectName("progressBarProgressoGeral")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 290, 501, 91))
        self.groupBox_5.setObjectName("groupBox_5")
        self.textEditConsole = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEditConsole.setGeometry(QtCore.QRect(10, 20, 481, 61))
        self.textEditConsole.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditConsole.setObjectName("textEditConsole")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(220, 10, 291, 61))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(160, 20, 51, 16))
        self.label_8.setObjectName("label_8")
        self.labelTamanho = QtWidgets.QLabel(self.groupBox_4)
        self.labelTamanho.setGeometry(QtCore.QRect(210, 20, 71, 16))
        self.labelTamanho.setText("")
        self.labelTamanho.setObjectName("labelTamanho")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 31, 16))
        self.label_11.setObjectName("label_11")
        self.labelNome = QtWidgets.QLabel(self.groupBox_4)
        self.labelNome.setGeometry(QtCore.QRect(50, 20, 91, 16))
        self.labelNome.setText("")
        self.labelNome.setObjectName("labelNome")
        self.tabWidget.raise_()
        self.pushButtonIniciar.raise_()
        self.pushButtonParar.raise_()
        self.pushButtonPausar.raise_()
        self.progressBarProgressoGeral.raise_()
        self.groupBox_5.raise_()
        self.groupBox_4.raise_()
        janela.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(janela)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 521, 21))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuSobre = QtWidgets.QMenu(self.menubar)
        self.menuSobre.setObjectName("menuSobre")
        self.menuIdioma = QtWidgets.QMenu(self.menubar)
        self.menuIdioma.setObjectName("menuIdioma")
        janela.setMenuBar(self.menubar)
        self.actionAbrir = QtWidgets.QAction(janela)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icones/Winrar/winrar-480.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbrir.setIcon(icon10)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionSalvar = QtWidgets.QAction(janela)
        self.actionSalvar.setEnabled(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icones/Sistema operacional/salvar-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSalvar.setIcon(icon11)
        self.actionSalvar.setObjectName("actionSalvar")
        self.actionAjuda = QtWidgets.QAction(janela)
        self.actionAjuda.setEnabled(False)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icones/Ajuda/ajuda-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAjuda.setIcon(icon12)
        self.actionAjuda.setObjectName("actionAjuda")
        self.actionSobre = QtWidgets.QAction(janela)
        self.actionSobre.setEnabled(False)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icones/Sobre/sobre-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSobre.setIcon(icon13)
        self.actionSobre.setObjectName("actionSobre")
        self.actionFechar = QtWidgets.QAction(janela)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icones/Saída/porta-aberta-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFechar.setIcon(icon14)
        self.actionFechar.setObjectName("actionFechar")
        self.actionThreads = QtWidgets.QAction(janela)
        self.actionThreads.setIcon(icon9)
        self.actionThreads.setObjectName("actionThreads")
        self.actionPortugues = QtWidgets.QAction(janela)
        self.actionPortugues.setEnabled(False)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icones/Países/brasil-480.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPortugues.setIcon(icon15)
        self.actionPortugues.setObjectName("actionPortugues")
        self.actionIngles = QtWidgets.QAction(janela)
        self.actionIngles.setEnabled(False)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("icones/Países/eua-480.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIngles.setIcon(icon16)
        self.actionIngles.setObjectName("actionIngles")
        self.actionAbrirProjeto = QtWidgets.QAction(janela)
        self.actionAbrirProjeto.setEnabled(False)
        self.actionAbrirProjeto.setIcon(icon6)
        self.actionAbrirProjeto.setObjectName("actionAbrirProjeto")
        self.menuArquivo.addAction(self.actionAbrir)
        self.menuArquivo.addAction(self.actionSalvar)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionAbrirProjeto)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionFechar)
        self.menuSobre.addAction(self.actionAjuda)
        self.menuSobre.addAction(self.actionSobre)
        self.menuIdioma.addAction(self.actionPortugues)
        self.menuIdioma.addAction(self.actionIngles)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuIdioma.menuAction())
        self.menubar.addAction(self.menuSobre.menuAction())

        self.retranslateUi(janela)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(janela)
    #----------------------------------------------Código adicionado manualmente-----------------------------------------------#
    #Imports    
        import run
        import packs
        import abrirArquivo
        import iniciarPrograma
        from functools import partial
        from PyQt5.QtWidgets import QMessageBox
    #--------------------------------------------------------------------------------------------------------------------------#
    #Threads
        self.threads = []
        self.abrir = abrirArquivo.abrir(self.labelNome, self.labelTamanho)
    #--------------------------------------------------------------------------------------------------------------------------#
    #Desabilita tabs
        self.tab_3.setEnabled(False)
        self.tab_2.setEnabled(False)
    #--------------------------------------------------------------------------------------------------------------------------#
    #Recebimento de sinal do iniciar
        def sinalIniciar(comando, valor):
            if comando == "apagar":
                self.textEditConsole.clear()

            if comando == "atualizarBarra":
                self.progressBarProgressoGeral.setValue(int(valor))

            if comando == "bloquear":
                self.menubar.setEnabled(False)
                self.tabWidget.setEnabled(False)
                self.pushButtonIniciar.setEnabled(False)

            if comando == "liberar":
                self.menubar.setEnabled(True)
                self.tabWidget.setEnabled(True)
                self.pushButtonIniciar.setEnabled(True)

            if comando == "msginformacao":
                msgBox = QMessageBox()
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setWindowTitle("Informação")
                msgBox.setText(valor)
                msgBox.setWindowIcon(QtGui.QIcon("./icones/Sobre/sobre-96.png"))
                msgBox.exec_()

            if comando == "msgerro":
                msgBox = QMessageBox()
                msgBox.setIcon(QMessageBox.Critical)
                msgBox.setWindowTitle("Erro !")
                msgBox.setText(valor)
                msgBox.setWindowIcon(QtGui.QIcon("./icones/Sistema operacional/excluir-96.png"))
                msgBox.exec_()
                
            if comando == "msgatencao":
                msgBox = QMessageBox()
                msgBox.setIcon(QMessageBox.Warning)
                msgBox.setWindowTitle("Atenção !")
                msgBox.setText(valor)
                msgBox.setWindowIcon(QtGui.QIcon("./icones/Sistema operacional/atencao-96.png"))
                msgBox.exec_()

            if comando == "console":
                self.textEditConsole.insertPlainText(valor)
    #--------------------------------------------------------------------------------------------------------------------------#
    #Botão Iniciar
        def iniciar():
            caracteres                      = []
            LimiteMinimo                    = self.spinBoxLimiteMinimo.value()
            LimiteMaximo                    = self.spinBoxLimiteMaximo.value()

            caracteres                      = packs.retornaCaracteres(caracteres, self.checkBoxTodos, 
                                                self.checkBoxLetrasMaiusculas, self.checkBoxLetrasMinusculas, 
                                                self.checkBoxLetrasAcentuadas, self.checkBoxNumeros, 
                                                self.checkBoxSimbolos, self.checkBoxEspaco)
            
            iniciar                         = iniciarPrograma.iniciar(self.abrir, self.pushButtonIniciar, 
                                                self.progressBarProgressoGeral, self.tabWidget, LimiteMinimo,
                                                LimiteMaximo, caracteres)

            iniciar.sinal.connect(sinalIniciar)
            self.threads.append(iniciar)
            iniciar.start()
        
        self.pushButtonIniciar.clicked.connect(iniciar)
    #--------------------------------------------------------------------------------------------------------------------------#        
    #Botão Parar
        def pararCracker():
            if len(self.threads) > 0:
                for thread in self.threads:
                    thread.stop()
                self.threads.clear()
                sinalIniciar("liberar", 0)
        
        self.pushButtonParar.clicked.connect(pararCracker)
    #--------------------------------------------------------------------------------------------------------------------------#        
    #Arquivo -> Abrir
        def abrir():
            self.abrir.run()
        
        self.actionAbrir.triggered.connect(abrir)
    #--------------------------------------------------------------------------------------------------------------------------#        
    #Arquivo -> Sair
        def sairDoPrograma():
            janela.close()
        
        self.actionFechar.triggered.connect(sairDoPrograma)
    #--------------------------------------------------------------------------------------------------------------------------#
    #Checkbox Todos os caracteres
        def todosCaracteres():
            if self.checkBoxTodos.isChecked():
                self.checkBoxLetrasMaiusculas.setEnabled(False)
                self.checkBoxLetrasMinusculas.setEnabled(False)
                self.checkBoxLetrasAcentuadas.setEnabled(False)
                self.checkBoxNumeros.setEnabled(False)
                self.checkBoxSimbolos.setEnabled(False)
                self.checkBoxEspaco.setEnabled(False)

            if not self.checkBoxTodos.isChecked():
                self.checkBoxLetrasMaiusculas.setEnabled(True)
                self.checkBoxLetrasMinusculas.setEnabled(True)
                self.checkBoxLetrasAcentuadas.setEnabled(True)
                self.checkBoxNumeros.setEnabled(True)
                self.checkBoxSimbolos.setEnabled(True)
                self.checkBoxEspaco.setEnabled(True)
        
        self.checkBoxTodos.clicked.connect(todosCaracteres)
    #--------------------------------------------------------------------------------------------------------------------------#
    def retranslateUi(self, janela):
        _translate = QtCore.QCoreApplication.translate
        janela.setWindowTitle(_translate("janela", "RAR Recovery"))
        self.groupBox_2.setTitle(_translate("janela", "Inicio e fim"))
        self.label.setText(_translate("janela", "Iniciar em:"))
        self.label_2.setText(_translate("janela", "Finalizar em:"))
        self.groupBox_3.setTitle(_translate("janela", "Tamanho da senha"))
        self.label_3.setText(_translate("janela", "Limite mínimo da senha:"))
        self.label_4.setText(_translate("janela", "Limite máximo da senha:"))
        self.label_5.setText(_translate("janela", "caractere(s)"))
        self.label_6.setText(_translate("janela", "caractere(s)"))
        self.groupBox.setTitle(_translate("janela", "Caracteres"))
        self.checkBoxLetrasMaiusculas.setText(_translate("janela", "Letras maiúsculas (A - Z)"))
        self.checkBoxLetrasMinusculas.setText(_translate("janela", "Letras minúsculas (a - z)"))
        self.checkBoxNumeros.setText(_translate("janela", "Números (0 - 9)"))
        self.checkBoxSimbolos.setText(_translate("janela", "Símbolos especiais (@, #, $...)"))
        self.checkBoxLetrasAcentuadas.setText(_translate("janela", "Letras acentuadas (ã, é, ç...)"))
        self.checkBoxEspaco.setText(_translate("janela", "Espaço"))
        self.checkBoxTodos.setText(_translate("janela", "Todos os caracteres"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("janela", "Força bruta"))
        self.pushButton_4.setText(_translate("janela", "Abrir"))
        self.pushButton_5.setText(_translate("janela", "Fechar"))
        self.groupBox_6.setTitle(_translate("janela", "Inicio e fim"))
        self.label_13.setText(_translate("janela", "Iniciar na linha:"))
        self.label_14.setText(_translate("janela", "Finalizar na linha:"))
        self.groupBox_7.setTitle(_translate("janela", "Informações do arquivo"))
        self.label_15.setText(_translate("janela", "Formato:"))
        self.label_16.setText(_translate("janela", "Tamanho:"))
        self.label_17.setText(_translate("janela", "xxx"))
        self.label_18.setText(_translate("janela", "xxx"))
        self.label_21.setText(_translate("janela", "Nome:"))
        self.label_22.setText(_translate("janela", "xxxxxxxxx"))
        self.label_23.setText(_translate("janela", "xxxxxxxxx"))
        self.label_26.setText(_translate("janela", "Número de linhas:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("janela", "Dicionário"))
        self.groupBox_9.setTitle(_translate("janela", "Gerenciamento de Threads"))
        self.radioButton_4.setText(_translate("janela", "Automático"))
        self.radioButton_5.setText(_translate("janela", "Manual"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("janela", "CPU"))
        self.progressBarProgressoGeral.setFormat(_translate("janela", "%p%"))
        self.groupBox_5.setTitle(_translate("janela", "Console"))
        self.textEditConsole.setHtml(_translate("janela", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.groupBox_4.setTitle(_translate("janela", "Informações do arquivo"))
        self.label_8.setText(_translate("janela", "Tamanho:"))
        self.label_11.setText(_translate("janela", "Nome:"))
        self.menuArquivo.setTitle(_translate("janela", "Arquivo"))
        self.menuSobre.setTitle(_translate("janela", "Info"))
        self.menuIdioma.setTitle(_translate("janela", "Idioma"))
        self.actionAbrir.setText(_translate("janela", "Abrir RAR/ZIP"))
        self.actionSalvar.setText(_translate("janela", "Salvar"))
        self.actionAjuda.setText(_translate("janela", "Ajuda"))
        self.actionSobre.setText(_translate("janela", "Sobre"))
        self.actionFechar.setText(_translate("janela", "Sair"))
        self.actionThreads.setText(_translate("janela", "Threads"))
        self.actionPortugues.setText(_translate("janela", "Português"))
        self.actionIngles.setText(_translate("janela", "Inglês"))
        self.actionAbrirProjeto.setText(_translate("janela", "Abrir projeto"))